{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Lag(Mean Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Is Service UP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_up", "legendFormat": "{{__name__}}" },
    { "expr": "mongodb_up", "legendFormat": "{{__name__}}" },
    { "expr": "redis_up", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}